# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHhdkObqkSjY2GpLcQ-YchSX7i7CCFrQ
"""

import streamlit as st
import pandas as pd
import time
import gemini_backend_v4 as backend

# ==========================================
# 1. PAGE CONFIG & CUSTOM CSS (Teal/White Theme)
# ==========================================
st.set_page_config(
    page_title="BPCL Scout | Alan Corp.",
    page_icon="⚽",
    layout="centered"
)

# Custom CSS for Teal Theme & Tactile Buttons
st.markdown("""
<style>
    /* Main Background & Text */
    .stApp {
        background-color: #F5F9F9; /* Very light teal/white smoke */
        color: #0F3D3D; /* Dark Teal Text */
    }

    /* Headers */
    h1, h2, h3 {
        color: #008080 !important; /* Teal Green */
        font-family: 'Helvetica Neue', sans-serif;
    }

    /* Custom Button Styling */
    div.stButton > button {
        background-color: #008080;
        color: white;
        border-radius: 12px;
        border: none;
        padding: 10px 24px;
        font-size: 16px;
        font-weight: bold;
        box-shadow: 0px 4px 6px rgba(0, 0, 0, 0.2);
        transition: all 0.1s ease-in-out;
        width: 100%;
    }

    /* Button Click Animation */
    div.stButton > button:active {
        transform: translateY(2px);
        box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.2);
        background-color: #006666;
    }

    /* Footer */
    .footer {
        position: fixed;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: #008080;
        color: white;
        text-align: center;
        padding: 10px;
        font-size: 12px;
        font-family: monospace;
    }
    .footer a {
        color: #A3E4E4;
        text-decoration: none;
    }

    /* Card Styling for Results */
    .result-card {
        background-color: white;
        padding: 20px;
        border-radius: 15px;
        box-shadow: 0px 4px 12px rgba(0,0,0,0.05);
        margin-bottom: 20px;
        border-left: 5px solid #008080;
    }
</style>
""", unsafe_allow_html=True)

# ==========================================
# 2. LOGO MAPPING
# ==========================================
# To use this, create a folder named 'logos' and name images EXACTLY like the team name
# e.g. "Nameless EU.png", "Kagaway.png"
def get_logo_path(team_name):
    # If using local files:
    # return f"logos/{team_name}.png"

    # For now, we return a placeholder icon or empty string if file missing
    return "⚽"

# ==========================================
# 3. LOAD SYSTEM (Cached for Speed)
# ==========================================
@st.cache_resource
def load_engine():
    # This runs your backend training ONCE when the app starts
    model, processed_data = backend.preprocess_and_train()
    return model, processed_data

# Sidebar for Context
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3233/3233497.png", width=100)
    st.title("League Context")
    st.info("""
    **BPCL Winter '26**
    - **Current Leader:** Kagaway
    - **Venue:** Neutral Grounds (No Home Adv)
    - **Engine:** Gemini 2.5 Flash + XGBoost
    """)
    st.write("---")
    st.write("System Status: 🟢 Online")

# ==========================================
# 4. MAIN INTERFACE
# ==========================================
st.title("🏆 BPCL Match Predictor")
st.markdown("### AI-Powered Tactical Scouting")

# Load the brain
with st.spinner("Booting up the Neural Engine..."):
    model, matches = load_engine()
    team_list = sorted(matches['home_team'].unique())

# Input Section
col1, col2 = st.columns(2)

with col1:
    st.markdown("#### Team A")
    team_a = st.selectbox("Select Team", team_list, key="t1")
    # st.image(get_logo_path(team_a), width=100) # Uncomment if you have images

with col2:
    st.markdown("#### Team B")
    team_b = st.selectbox("Select Team", team_list, key="t2", index=1)
    # st.image(get_logo_path(team_b), width=100) # Uncomment if you have images

# Predict Button
st.write("")
st.write("")
if st.button("GENERATE SCOUT REPORT"):
    if team_a == team_b:
        st.error("Please select two different teams.")
    else:
        # Progress Bar for effect
        progress_text = "Analyzing historical match logs..."
        my_bar = st.progress(0, text=progress_text)
        for percent_complete in range(100):
            time.sleep(0.01)
            my_bar.progress(percent_complete + 1, text="Consulting Gemini Tactical Engine...")
        time.sleep(0.5)
        my_bar.empty()

        # Call Backend
        report = backend.run_ai_prediction(team_a, team_b, model, matches)

        # Display Results
        st.markdown(f"""
        <div class="result-card">
            <h3>📊 Tactical Analysis</h3>
            {report.replace(chr(10), '<br>')}
        </div>
        """, unsafe_allow_html=True)

        st.success("Analysis Complete.")

# ==========================================
# 5. FOOTER
# ==========================================
st.markdown("""
<div class="footer">
    Built by <b>Alan Corp.</b><br>
    Contact: <a href="mailto:aelanlockin@gmail.com">aelanlockin@gmail.com</a>
</div>
""", unsafe_allow_html=True)